### ISSUE TITLE
Choose a Good Name

### ISSUE THREAD

**Issue by nprail** [Filiosoft/s3d#2]
Currently, due to my lack of creativity, we have named this project `s3d`. That is an incredibly boring name. It stands for S3 Deploy. Again, very boring. We would love to give it a new name that sounds good. If you have an idea, feel free to comment below!

These are the requirements for the name:

- Short. Less than 5 characters. The shorter the better.
- Available on NPM.
- Available domain name. (That sounds good)
- Shouldn't conflict with any preinstalled binaries.

### Tasks
- [x] Come up with a new name
- [ ] Replace `s3d` with the new name everywhere in the source
- [x] Rename repositories
- [x] Rename remaining references to `s3d`

**Comment by nprail** [comment]
Here's an idea! `maxup`! It's 5 characters, available on NPM, and `maxup.sh` is available. Also, we can alias the binary so `max` works as well. 

- [NPM](https://www.npmjs.com/package/maxup)
- [maxup.sh](https://www.namecheap.com/domains/registration/results.aspx?domain=maxup.sh)
